import type { WorkflowJSON } from "@/types/workflow";
import { getWorkflowExportContent, getWorkflowExportFileName } from "@/lib/persistence";

export const CLAUDE_PLUGIN_ROOT_REFERENCE = "${CLAUDE_PLUGIN_ROOT}";
export const CLAUDE_PLUGIN_AUTHOR = { name: "Nexus Workflow Studio" } as const;

function slugifyPluginSegment(raw: string, fallback: string): string {
  const slug = raw
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-+|-+$/g, "");

  return slug || fallback;
}

function truncatePluginName(name: string): string {
  return name.slice(0, 64).replace(/-+$/g, "") || "nexus-workflow";
}

export function buildClaudePluginName(workflowName: string): string {
  const slug = slugifyPluginSegment(workflowName, "workflow");
  return truncatePluginName(`nexus-${slug}`);
}

export function buildClaudePluginSkillName(raw: string, fallback = "workflow"): string {
  return slugifyPluginSegment(raw, fallback);
}

export function buildClaudePluginManifest(workflow: Pick<WorkflowJSON, "name"> & { description?: string }): string {
  const manifest = {
    name: buildClaudePluginName(workflow.name),
    description: workflow.description?.trim() || `Nexus workflow plugin for ${workflow.name}`,
    author: CLAUDE_PLUGIN_AUTHOR,
    keywords: ["nexus", "workflow", "claude-plugin"],
  };

  return `${JSON.stringify(manifest, null, 2)}\n`;
}

export function buildClaudePluginWorkflowJsonPath(workflow: Pick<WorkflowJSON, "name">): string {
  return `nexus/${getWorkflowExportFileName(workflow)}`;
}

export function buildClaudePluginWorkflowJson(workflow: WorkflowJSON): string {
  return getWorkflowExportContent(workflow);
}

function stripMarkdownFrontmatter(markdown: string): string {
  if (!markdown.startsWith("---\n")) return markdown;
  const end = markdown.indexOf("\n---", 4);
  if (end < 0) return markdown;
  const after = markdown.slice(end + "\n---".length);
  return after.replace(/^\n+/, "");
}

function escapeFrontmatterValue(value: string): string {
  return value.replace(/[\r\n]+/g, " ").trim() || "Nexus workflow";
}

export function buildClaudeWorkflowSkillMarkdown(
  workflow: Pick<WorkflowJSON, "name"> & { description?: string },
  commandMarkdown: string,
  skillName = "run",
): string {
  const description = escapeFrontmatterValue(workflow.description?.trim() || workflow.name || skillName);
  const body = stripMarkdownFrontmatter(commandMarkdown);
  return [
    "---",
    `name: ${skillName}`,
    `description: ${description}`,
    "disable-model-invocation: true",
    "---",
    "",
    body.trimEnd(),
    "",
  ].join("\n");
}

export function buildClaudePluginReadme(workflow: WorkflowJSON): string {
  const pluginName = buildClaudePluginName(workflow.name);
  return `# ${workflow.name}\n\nGenerated by Nexus Workflow Studio as a Claude/Cowork plugin package.\n\n## Install\n\n- **Cowork custom plugin upload:** ZIP this plugin folder with \`.claude-plugin/plugin.json\` at the ZIP root, then upload it as a custom plugin.\n- **Local Claude Code:** run \`claude --plugin-dir <plugin-dir>\` from the parent directory or point Claude Code at this plugin folder.\n- **Marketplace repository:** copy this folder into a Cowork marketplace repository when you are ready to publish it.\n\n## Run\n\nInvoke the workflow after installation with:\n\n\`/${pluginName}:run\`\n\n## Package contents\n\n- \`.claude-plugin/plugin.json\` — Claude plugin manifest.\n- \`skills/run/SKILL.md\` — main Nexus workflow skill.\n- \`agents/\` — generated Claude-compatible agents.\n- \`skills/<skill-name>/\` — bundled connected skills and scripts.\n- \`docs/\` — bundled documents referenced by generated agents and workflow details.\n- \`nexus/\` — round-trip Nexus workflow JSON.\n`;
}

export function buildClaudeSkillReferencePath(skillName: string): string {
  return `${CLAUDE_PLUGIN_ROOT_REFERENCE}/skills/${skillName}/SKILL.md`;
}

export function buildClaudeDocsReferencePath(fileName: string): string {
  return `${CLAUDE_PLUGIN_ROOT_REFERENCE}/docs/${fileName}`;
}

export function buildClaudeSkillScriptReferencePath(skillName: string, scriptFileName: string): string {
  return `${CLAUDE_PLUGIN_ROOT_REFERENCE}/skills/${skillName}/scripts/${scriptFileName}`;
}
