import {
  getGenerationTarget,
  type GenerationTargetId,
} from "@/lib/generation-targets";
import type { GeneratedFile } from "@/lib/workflow-generator";

const TARGET_CLI: Record<GenerationTargetId, { bin: string; addDirFlag: string }> = {
  "claude-code": { bin: "claude", addDirFlag: "--add-dir" },
  opencode: { bin: "opencode", addDirFlag: "--add-dir" },
  pi: { bin: "pi", addDirFlag: "--add-dir" },
};

export const WORKFLOW_EXPORT_MARKER_PATH = ".nexus-workflow-export";

export function buildWorkflowExportMarker(
  workflowName: string,
  target: GenerationTargetId,
  rootDir: string,
): string {
  return `# NexusWorkflowStudio generated workflow export
workflow=${workflowName}
target=${target}
rootDir=${rootDir}
`;
}

function buildBashScript(
  name: string,
  target: GenerationTargetId,
  bin: string,
  addDirFlag: string,
  rootDir: string,
): string {
  return `#!/usr/bin/env bash
# Generated by NexusWorkflowStudio
# Keep this runner inside its exported bundle.
# Run from your repository root: bash /path/to/export/run-${name}.sh [args...]
set -euo pipefail
REPO_DIR="$(pwd)"
SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"

MARKER_FILE="$SCRIPT_DIR/${WORKFLOW_EXPORT_MARKER_PATH}"
COMMAND_FILE="$SCRIPT_DIR/${rootDir}/commands/${name}.md"

if [[ ! -f "$MARKER_FILE" ]] || ! grep -qx "workflow=${name}" "$MARKER_FILE" || ! grep -qx "target=${target}" "$MARKER_FILE"; then
  echo "This runner must stay beside its Nexus workflow export bundle." >&2
  echo "Extract the ZIP into its own directory, then run this script from your repository root." >&2
  exit 1
fi

if [[ ! -f "$COMMAND_FILE" ]]; then
  echo "Missing generated command file: $COMMAND_FILE" >&2
  echo "The exported ${rootDir} folder must stay next to this runner." >&2
  exit 1
fi

cd "$SCRIPT_DIR"
echo "/${name}" | ${bin} ${addDirFlag} "$REPO_DIR" "$@"
`;
}

function buildBatchScript(
  name: string,
  target: GenerationTargetId,
  bin: string,
  addDirFlag: string,
  rootDir: string,
): string {
  return `@echo off
set REPO_DIR=%CD%
set SCRIPT_DIR=%~dp0
set MARKER_FILE=%SCRIPT_DIR%${WORKFLOW_EXPORT_MARKER_PATH}
set COMMAND_FILE=%SCRIPT_DIR%${rootDir}\\commands\\${name}.md
if not exist "%MARKER_FILE%" (
  echo This runner must stay beside its Nexus workflow export bundle. 1>&2
  echo Extract the ZIP into its own directory, then run this script from your repository root. 1>&2
  exit /b 1
)
findstr /x /c:"workflow=${name}" "%MARKER_FILE%" >nul || (
  echo This runner does not match the exported workflow bundle. 1>&2
  exit /b 1
)
findstr /x /c:"target=${target}" "%MARKER_FILE%" >nul || (
  echo This runner does not match the exported target bundle. 1>&2
  exit /b 1
)
if not exist "%COMMAND_FILE%" (
  echo Missing generated command file: %COMMAND_FILE% 1>&2
  echo The exported ${rootDir} folder must stay next to this runner. 1>&2
  exit /b 1
)
cd /d "%SCRIPT_DIR%"
${bin} ${addDirFlag} "%REPO_DIR%" "/${name}" %*
`;
}

export function generateRunScriptFiles(
  workflowName: string,
  target: GenerationTargetId,
): GeneratedFile[] {
  const cli = TARGET_CLI[target];
  const rootDir = getGenerationTarget(target).rootDir;
  return [
    {
      path: WORKFLOW_EXPORT_MARKER_PATH,
      content: buildWorkflowExportMarker(workflowName, target, rootDir),
    },
    {
      path: `run-${workflowName}.sh`,
      content: buildBashScript(workflowName, target, cli.bin, cli.addDirFlag, rootDir),
    },
    {
      path: `run-${workflowName}.bat`,
      content: buildBatchScript(workflowName, target, cli.bin, cli.addDirFlag, rootDir),
    },
  ];
}
