import type { GenerationTargetId } from "@/lib/generation-targets";
import type { GeneratedFile } from "@/lib/workflow-generator";

const TARGET_CLI: Record<GenerationTargetId, { bin: string; addDirFlag: string }> = {
  "claude-code": { bin: "claude", addDirFlag: "--add-dir" },
  opencode: { bin: "opencode", addDirFlag: "--add-dir" },
  pi: { bin: "pi", addDirFlag: "--add-dir" },
};

function buildBashScript(name: string, bin: string, addDirFlag: string): string {
  return `#!/usr/bin/env bash
# Generated by NexusWorkflowStudio
# Run from your repository root: bash run-${name}.sh [args...]
REPO_DIR="$(pwd)"
SCRIPT_DIR="$(cd "$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"
echo "/${name}" | ${bin} ${addDirFlag} "$REPO_DIR" "$@"
`;
}

function buildBatchScript(name: string, bin: string, addDirFlag: string): string {
  return `@echo off
set REPO_DIR=%CD%
set SCRIPT_DIR=%~dp0
cd /d "%SCRIPT_DIR%"
${bin} ${addDirFlag} "%REPO_DIR%" "/${name}" %*
`;
}

export function generateRunScriptFiles(
  workflowName: string,
  target: GenerationTargetId,
): GeneratedFile[] {
  if (target === "claude-code") return [];

  const cli = TARGET_CLI[target];
  return [
    {
      path: `run-${workflowName}.sh`,
      content: buildBashScript(workflowName, cli.bin, cli.addDirFlag),
    },
    {
      path: `run-${workflowName}.bat`,
      content: buildBatchScript(workflowName, cli.bin, cli.addDirFlag),
    },
  ];
}
