// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddBrainFeedbackReducer from "../add_brain_feedback_reducer";
import ApplyWorkflowOpsReducer from "../apply_workflow_ops_reducer";
import CreateInviteReducer from "../create_invite_reducer";
import CreateWorkflowReducer from "../create_workflow_reducer";
import CreateWorkspaceReducer from "../create_workspace_reducer";
import DeleteBrainDocReducer from "../delete_brain_doc_reducer";
import DeleteWorkflowReducer from "../delete_workflow_reducer";
import DeleteWorkspaceReducer from "../delete_workspace_reducer";
import ImportBrainDocReducer from "../import_brain_doc_reducer";
import ImportWorkflowSnapshotReducer from "../import_workflow_snapshot_reducer";
import ImportWorkspaceReducer from "../import_workspace_reducer";
import JoinWorkspaceReducer from "../join_workspace_reducer";
import RecordBrainViewReducer from "../record_brain_view_reducer";
import RenameWorkflowReducer from "../rename_workflow_reducer";
import RenameWorkspaceReducer from "../rename_workspace_reducer";
import RestoreBrainDocVersionReducer from "../restore_brain_doc_version_reducer";
import SaveBrainDocReducer from "../save_brain_doc_reducer";
import UpdatePresenceReducer from "../update_presence_reducer";
import UpdateWorkflowUiStateReducer from "../update_workflow_ui_state_reducer";

export type AddBrainFeedbackParams = __Infer<typeof AddBrainFeedbackReducer>;
export type ApplyWorkflowOpsParams = __Infer<typeof ApplyWorkflowOpsReducer>;
export type CreateInviteParams = __Infer<typeof CreateInviteReducer>;
export type CreateWorkflowParams = __Infer<typeof CreateWorkflowReducer>;
export type CreateWorkspaceParams = __Infer<typeof CreateWorkspaceReducer>;
export type DeleteBrainDocParams = __Infer<typeof DeleteBrainDocReducer>;
export type DeleteWorkflowParams = __Infer<typeof DeleteWorkflowReducer>;
export type DeleteWorkspaceParams = __Infer<typeof DeleteWorkspaceReducer>;
export type ImportBrainDocParams = __Infer<typeof ImportBrainDocReducer>;
export type ImportWorkflowSnapshotParams = __Infer<typeof ImportWorkflowSnapshotReducer>;
export type ImportWorkspaceParams = __Infer<typeof ImportWorkspaceReducer>;
export type JoinWorkspaceParams = __Infer<typeof JoinWorkspaceReducer>;
export type RecordBrainViewParams = __Infer<typeof RecordBrainViewReducer>;
export type RenameWorkflowParams = __Infer<typeof RenameWorkflowReducer>;
export type RenameWorkspaceParams = __Infer<typeof RenameWorkspaceReducer>;
export type RestoreBrainDocVersionParams = __Infer<typeof RestoreBrainDocVersionReducer>;
export type SaveBrainDocParams = __Infer<typeof SaveBrainDocReducer>;
export type UpdatePresenceParams = __Infer<typeof UpdatePresenceReducer>;
export type UpdateWorkflowUiStateParams = __Infer<typeof UpdateWorkflowUiStateReducer>;
