export { Fields as PromptFields }       from "@/nodes/prompt/fields";
export { Fields as ScriptFields }       from "@/nodes/script/fields";
export { Fields as SubAgentFields }     from "@/nodes/agent/fields";
export { Fields as SubWorkflowFields } from "@/nodes/sub-workflow/fields";
export { Fields as SkillFields }        from "@/nodes/skill/fields";
export { Fields as DocumentFields }     from "@/nodes/document/fields";
export { Fields as McpToolFields }      from "@/nodes/mcp-tool/fields";
export { Fields as IfElseFields }       from "@/nodes/if-else/fields";
export { Fields as SwitchFields }       from "@/nodes/switch/fields";
export { Fields as AskUserFields }      from "@/nodes/ask-user/fields";
export { TypeSpecificFields }           from "./type-specific-fields";
export { detectVariables, detectVarCounts, DetectedVariablesPanel } from "@/nodes/shared/variable-utils";
export type { FormRegister, FormControl, FormSetValue, FormErrors } from "@/nodes/shared/form-types";