"use client";
import { Bot, GripHorizontal, Minimize2, Plus, X } from "lucide-react";
import { cn } from "@/lib/utils";
import { WORKFLOW_PANEL_SHELL_BASE_CLASS } from "@/components/workflow/panel-primitives";
import { useSidekickStore } from "@/store/sidekick";
import { useSidekickPosition } from "./use-sidekick-position";
import { SidekickMessages } from "./messages";
import { SidekickInputBar } from "./input-bar";
export function SidekickPanel() { const { style, onPointerDown } = useSidekickPosition(); const open = useSidekickStore((s) => s.panelOpen); const collapsed = useSidekickStore((s) => s.panelCollapsed); const messages = useSidekickStore((s) => s.messages); const status = useSidekickStore((s) => s.status); const error = useSidekickStore((s) => s.error); const setOpen = useSidekickStore((s) => s.setPanelOpen); const setCollapsed = useSidekickStore((s) => s.setPanelCollapsed); const newConversation = useSidekickStore((s) => s.newConversation); if (!open) return null; if (collapsed) return <button style={style} onClick={() => setCollapsed(false)} className="absolute z-30 rounded-full border border-violet-500 bg-zinc-950 px-4 py-2 text-sm text-zinc-100 shadow-xl"><Bot className="mr-2 inline" size={16}/>AI side-kick</button>; return <aside style={style} className={cn("absolute z-30 h-[min(680px,calc(100vh-56px))] w-[min(420px,calc(100vw-32px))]", WORKFLOW_PANEL_SHELL_BASE_CLASS)} aria-label="AI side-kick panel"><header onPointerDown={onPointerDown} className="flex cursor-grab items-center gap-2 border-b border-zinc-800 px-3 py-2 text-zinc-100"><GripHorizontal size={14}/><Bot size={16}/><b className="text-sm">AI side-kick</b><span className="ml-auto rounded bg-zinc-800 px-2 py-0.5 text-[11px] text-zinc-300">{status}</span><button aria-label="New side-kick conversation" onClick={(e) => { e.stopPropagation(); void newConversation(); }}><Plus size={16}/></button><button aria-label="Collapse side-kick" onClick={(e) => { e.stopPropagation(); setCollapsed(true); }}><Minimize2 size={16}/></button><button aria-label="Close side-kick" onClick={(e) => { e.stopPropagation(); setOpen(false); }}><X size={16}/></button></header>{error && <div className="border-b border-red-900 bg-red-950/60 px-3 py-2 text-xs text-red-200">{error}</div>}<SidekickMessages messages={messages}/><SidekickInputBar/></aside>; }
