export enum SubAgentModel {
  Inherit             = "inherit",
  // Anthropic Claude
  ClaudeHaiku45       = "claude-haiku-4.5",
  ClaudeOpus45        = "claude-opus-4.5",
  ClaudeOpus46        = "claude-opus-4.6",
  ClaudeOpus41        = "claude-opus-41",
  ClaudeSonnet4       = "claude-sonnet-4",
  ClaudeSonnet45      = "claude-sonnet-4.5",
  ClaudeSonnet46      = "claude-sonnet-4.6",
  // Google Gemini
  Gemini25Pro         = "gemini-2.5-pro",
  Gemini3FlashPreview = "gemini-3-flash-preview",
  Gemini3ProPreview   = "gemini-3-pro-preview",
  Gemini31ProPreview  = "gemini-3.1-pro-preview",
  // OpenAI
  GPT41               = "gpt-4.1",
  GPT4o               = "gpt-4o",
  GPT5                = "gpt-5",
  GPT5Mini            = "gpt-5-mini",
  GPT51               = "gpt-5.1",
  GPT51Codex          = "gpt-5.1-codex",
  GPT51CodexMax       = "gpt-5.1-codex-max",
  GPT51CodexMini      = "gpt-5.1-codex-mini",
  GPT52               = "gpt-5.2",
  GPT52Codex          = "gpt-5.2-codex",
}

/** Human-readable display names for each model */
export const MODEL_DISPLAY_NAMES: Record<SubAgentModel, string> = {
  [SubAgentModel.Inherit]:             "Inherit from workflow",
  [SubAgentModel.ClaudeHaiku45]:       "Claude Haiku 4.5",
  [SubAgentModel.ClaudeOpus45]:        "Claude Opus 4.5",
  [SubAgentModel.ClaudeOpus46]:        "Claude Opus 4.6",
  [SubAgentModel.ClaudeOpus41]:        "Claude Opus 4.1",
  [SubAgentModel.ClaudeSonnet4]:       "Claude Sonnet 4",
  [SubAgentModel.ClaudeSonnet45]:      "Claude Sonnet 4.5",
  [SubAgentModel.ClaudeSonnet46]:      "Claude Sonnet 4.6",
  [SubAgentModel.Gemini25Pro]:         "Gemini 2.5 Pro",
  [SubAgentModel.Gemini3FlashPreview]: "Gemini 3 Flash Preview",
  [SubAgentModel.Gemini3ProPreview]:   "Gemini 3 Pro Preview",
  [SubAgentModel.Gemini31ProPreview]:  "Gemini 3.1 Pro Preview",
  [SubAgentModel.GPT41]:              "GPT 4.1",
  [SubAgentModel.GPT4o]:              "GPT 4o",
  [SubAgentModel.GPT5]:               "GPT 5",
  [SubAgentModel.GPT5Mini]:           "GPT 5 Mini",
  [SubAgentModel.GPT51]:              "GPT 5.1",
  [SubAgentModel.GPT51Codex]:         "GPT 5.1 Codex",
  [SubAgentModel.GPT51CodexMax]:      "GPT 5.1 Codex Max",
  [SubAgentModel.GPT51CodexMini]:     "GPT 5.1 Codex Mini",
  [SubAgentModel.GPT52]:              "GPT 5.2",
  [SubAgentModel.GPT52Codex]:         "GPT 5.2 Codex",
};

/** Cost multiplier for each model (relative to baseline 1.0x) */
export const MODEL_COST_MULTIPLIER: Record<SubAgentModel, number> = {
  [SubAgentModel.Inherit]:             1.0,
  [SubAgentModel.ClaudeHaiku45]:       0.33,
  [SubAgentModel.ClaudeOpus45]:        3.0,
  [SubAgentModel.ClaudeOpus46]:        3.0,
  [SubAgentModel.ClaudeOpus41]:        3.0,
  [SubAgentModel.ClaudeSonnet4]:       1.0,
  [SubAgentModel.ClaudeSonnet45]:      1.0,
  [SubAgentModel.ClaudeSonnet46]:      1.0,
  [SubAgentModel.Gemini25Pro]:         1.0,
  [SubAgentModel.Gemini3FlashPreview]: 0.33,
  [SubAgentModel.Gemini3ProPreview]:   1.0,
  [SubAgentModel.Gemini31ProPreview]:  1.0,
  [SubAgentModel.GPT41]:              0.5,
  [SubAgentModel.GPT4o]:              0.5,
  [SubAgentModel.GPT5]:               2.0,
  [SubAgentModel.GPT5Mini]:           0.33,
  [SubAgentModel.GPT51]:              1.0,
  [SubAgentModel.GPT51Codex]:         1.0,
  [SubAgentModel.GPT51CodexMax]:      2.0,
  [SubAgentModel.GPT51CodexMini]:     0.33,
  [SubAgentModel.GPT52]:              1.0,
  [SubAgentModel.GPT52Codex]:         1.0,
};

export enum SubAgentMemory {
  Default = "-",
  Local   = "local",
  User    = "user",
  Project = "project",
}