import { z } from "zod/v4";
import { nanoid } from "nanoid";
import { useWorkflowStore } from "@/store/workflow";
import { useSavedWorkflowsStore } from "@/store/library";
import { useKnowledgeStore } from "@/store/knowledge";
import { useCollabStore } from "@/store/collaboration/collab-store";
import { createNodeFromType, NODE_REGISTRY } from "@/lib/node-registry";
import { normalizeWorkflowConnection } from "@/lib/workflow-connections";
import { NON_DELETABLE_NODE_TYPES, WorkflowNodeType, type NodeType, type WorkflowNode, type WorkflowEdge, type WorkflowNodeData } from "@/types/workflow";
import type { CanvasMode } from "@/store/workflow";
import type { ParsedActionCall, ToolDefinition, ToolResult } from "./types";

const ok = (id: string, name: string, result?: unknown): ToolResult => ({ id, name, ok: true, result });
const err = (id: string, name: string, code: string, message: string): ToolResult => ({ id, name, ok: false, error: { code, message } });
const ContextArgs = z.object({}).passthrough();
const defineTool = <Schema extends z.ZodType>(definition: ToolDefinition<Schema>) => definition;
function currentNodes() { const s = useWorkflowStore.getState(); return s.activeSubWorkflowNodeId ? s.subWorkflowNodes : s.nodes; }
function currentEdges() { const s = useWorkflowStore.getState(); return s.activeSubWorkflowNodeId ? s.subWorkflowEdges : s.edges; }
function commit(nodes: WorkflowNode[], edges: WorkflowEdge[]) { const s = useWorkflowStore.getState(); if (s.activeSubWorkflowNodeId) { s.setSubWorkflowNodes(nodes); s.setSubWorkflowEdges(edges); s.updateSubWorkflowData(s.activeSubWorkflowNodeId, nodes, edges); } else useWorkflowStore.setState({ nodes, edges }); }
function ensureOwner(write?: boolean) { const c = useCollabStore.getState(); return !write || !c.roomId || c.isOwner; }

export const TOOL_DEFINITIONS = [
  defineTool({ name: "getCurrentWorkflow", description: "Return current workflow summary", schema: ContextArgs, handler: () => ok("", "", useWorkflowStore.getState().getWorkflowJSON()) }),
  defineTool({ name: "getNode", description: "Return a node by id", schema: z.object({ id: z.string() }), handler: ({ id }) => ok("", "", currentNodes().find((n) => n.id === id) ?? null) }),
  defineTool({ name: "listNodes", description: "List visible nodes", schema: ContextArgs, handler: () => ok("", "", currentNodes()) }),
  defineTool({ name: "listEdges", description: "List visible edges", schema: ContextArgs, handler: () => ok("", "", currentEdges()) }),
  defineTool({ name: "listNodeTypes", description: "List available node types", schema: ContextArgs, handler: () => ok("", "", Object.values(NODE_REGISTRY).map((n) => ({ type: n.type, label: n.displayName, description: n.description }))) }),
  defineTool({ name: "getViewState", description: "Return editor view state", schema: ContextArgs, handler: () => { const s = useWorkflowStore.getState(); return ok("", "", { selectedNodeId: s.selectedNodeId, activeSubWorkflowNodeId: s.activeSubWorkflowNodeId, subWorkflowStack: s.subWorkflowStack, canvasMode: s.canvasMode }); } }),
  defineTool({ name: "listSavedWorkflows", description: "List saved workflows", schema: ContextArgs, handler: () => ok("", "", useSavedWorkflowsStore.getState().entries) }),
  defineTool({ name: "listKnowledgeDocs", description: "List Brain documents", schema: ContextArgs, handler: () => ok("", "", useKnowledgeStore.getState().docs) }),
  defineTool({ name: "addNode", description: "Add a node", write: true, schema: z.object({ type: z.string(), position: z.object({ x: z.number(), y: z.number() }).optional(), data: z.record(z.string(), z.unknown()).optional() }), handler: ({ type, position, data }) => { const t = type as NodeType; if (!NODE_REGISTRY[t] || t === WorkflowNodeType.Start) throw new Error("Unsupported node type"); const node = createNodeFromType(t, position ?? { x: 320 + currentNodes().length * 20, y: 220 + currentNodes().length * 20 }) as WorkflowNode; node.data = { ...node.data, ...(data ?? {}) } as WorkflowNodeData; commit([...currentNodes(), node], currentEdges()); return ok("", "", { nodeId: node.id }); } }),
  defineTool({ name: "updateNodeData", description: "Patch node data", write: true, schema: z.object({ id: z.string(), data: z.record(z.string(), z.unknown()) }), handler: ({ id, data }) => { const nodes = currentNodes(); if (!nodes.some((n) => n.id === id)) return err("", "", "node_not_found", `Node ${id} not found`); commit(nodes.map((n) => n.id === id ? { ...n, data: { ...n.data, ...data } as WorkflowNodeData } : n), currentEdges()); return ok("", "", { nodeId: id }); } }),
  defineTool({ name: "connectNodes", description: "Connect two nodes", write: true, schema: z.object({ source: z.string(), target: z.string(), sourceHandle: z.string().optional(), targetHandle: z.string().optional() }), handler: (a) => { const edges = normalizeWorkflowConnection({ connection: { source: a.source, target: a.target, sourceHandle: a.sourceHandle ?? null, targetHandle: a.targetHandle ?? null }, nodes: currentNodes(), edges: currentEdges() }); if (!edges) return err("", "", "invalid_connection", "Connection could not be created"); commit(currentNodes(), edges); return ok("", "", { edgeCount: edges.length }); } }),
  defineTool({ name: "selectNode", description: "Select node", write: true, schema: z.object({ id: z.string().nullable() }), handler: ({ id }) => { useWorkflowStore.getState().selectNode(id); return ok("", "", { selectedNodeId: id }); } }),
  defineTool({ name: "selectAll", description: "Select all nodes", write: true, schema: ContextArgs, handler: () => { const nodes = currentNodes().map((n) => ({ ...n, selected: true })); commit(nodes, currentEdges()); return ok("", "", { count: nodes.length }); } }),
  defineTool({ name: "duplicateNode", description: "Duplicate node", write: true, schema: z.object({ id: z.string() }), handler: ({ id }) => { const n = currentNodes().find((node) => node.id === id); if (!n) return err("", "", "node_not_found", `Node ${id} not found`); const copy: WorkflowNode = { ...n, id: `${n.data.type}-${nanoid(8)}`, position: { x: n.position.x + 40, y: n.position.y + 40 }, data: { ...n.data, name: `${n.data.name} copy` } as WorkflowNodeData }; commit([...currentNodes(), copy], currentEdges()); return ok("", "", { nodeId: copy.id }); } }),
  defineTool({ name: "setName", description: "Set workflow name", write: true, schema: z.object({ name: z.string() }), handler: ({ name }) => { useWorkflowStore.getState().setName(name); return ok("", "", { name }); } }),
  defineTool({ name: "openPropertiesPanel", description: "Open properties panel", write: true, schema: z.object({ id: z.string() }), handler: ({ id }) => { useWorkflowStore.getState().openPropertiesPanel(id); return ok("", "", { id }); } }),
  defineTool({ name: "closePropertiesPanel", description: "Close properties panel", write: true, schema: ContextArgs, handler: () => { useWorkflowStore.getState().closePropertiesPanel(); return ok("", ""); } }),
  defineTool({ name: "openSubWorkflow", description: "Open a sub-workflow", write: true, schema: z.object({ id: z.string() }), handler: ({ id }) => { useWorkflowStore.getState().openSubWorkflow(id); return ok("", "", { id }); } }),
  defineTool({ name: "closeSubWorkflow", description: "Close active sub-workflow", write: true, schema: ContextArgs, handler: () => { useWorkflowStore.getState().closeSubWorkflow(); return ok("", ""); } }),
  defineTool({ name: "navigateToBreadcrumb", description: "Navigate sub-workflow breadcrumb", write: true, schema: z.object({ index: z.number().int() }), handler: ({ index }) => { useWorkflowStore.getState().navigateToBreadcrumb(index); return ok("", "", { index }); } }),
  defineTool({ name: "groupIntoSubWorkflow", description: "Group selected nodes into sub-workflow", write: true, schema: z.object({ nodeIds: z.array(z.string()) }), handler: ({ nodeIds }) => { useWorkflowStore.getState().groupIntoSubWorkflow(nodeIds); return ok("", "", { nodeIds }); } }),
  defineTool({ name: "setCanvasMode", description: "Set canvas mode", write: true, schema: z.object({ mode: z.enum(["hand", "selection"]) }), handler: ({ mode }) => { useWorkflowStore.getState().setCanvasMode(mode as CanvasMode); return ok("", "", { mode }); } }),
  defineTool({ name: "fitView", description: "Request fit view", write: true, schema: ContextArgs, handler: () => { if (typeof window !== "undefined") window.dispatchEvent(new CustomEvent("nexus:fit-view")); return ok("", "", { requested: true }); } }),
  defineTool({ name: "autoLayout", description: "Request auto layout", write: true, schema: ContextArgs, handler: () => { if (typeof window !== "undefined") window.dispatchEvent(new CustomEvent("nexus:auto-layout")); return ok("", "", { requested: true }); } }),
  defineTool({ name: "saveWorkflow", description: "Save workflow to library", write: true, schema: ContextArgs, handler: () => { const wf = useWorkflowStore.getState().getWorkflowJSON(); const id = useSavedWorkflowsStore.getState().save(wf); return ok("", "", { id }); } }),
  defineTool({ name: "markWorkflowSaved", description: "Mark workflow saved", write: true, schema: ContextArgs, handler: () => { useWorkflowStore.getState().markWorkflowSaved(); return ok("", ""); } }),
  defineTool({ name: "openLibrary", description: "Open library", write: true, schema: ContextArgs, handler: () => { useSavedWorkflowsStore.getState().openSidebar(); return ok("", ""); } }),
  defineTool({ name: "closeLibrary", description: "Close library", write: true, schema: ContextArgs, handler: () => { useSavedWorkflowsStore.getState().closeSidebar(); return ok("", ""); } }),
  defineTool({ name: "openKnowledgePanel", description: "Open Brain panel", write: true, schema: ContextArgs, handler: () => { useKnowledgeStore.getState().openPanel(); return ok("", ""); } }),
  defineTool({ name: "closeKnowledgePanel", description: "Close Brain panel", write: true, schema: ContextArgs, handler: () => { useKnowledgeStore.getState().closePanel(); return ok("", ""); } }),
  defineTool({ name: "deleteNode", description: "Delete a node", destructive: true, write: true, schema: z.object({ id: z.string() }), handler: ({ id }) => { const nodes = currentNodes(); const node = nodes.find((n) => n.id === id); if (!node || NON_DELETABLE_NODE_TYPES.has(node.data.type)) return err("", "", "node_not_deletable", `Node ${id} cannot be deleted`); commit(nodes.filter((n) => n.id !== id), currentEdges().filter((e) => e.source !== id && e.target !== id)); return ok("", "", { nodeId: id }); } }),
  defineTool({ name: "deleteEdge", description: "Delete an edge", destructive: true, write: true, schema: z.object({ id: z.string() }), handler: ({ id }) => { const before = currentEdges(); commit(currentNodes(), before.filter((e) => e.id !== id)); return before.some((e) => e.id === id) ? ok("", "", { edgeId: id }) : err("", "", "edge_not_found", `Edge ${id} not found`); } }),
];
export function getToolCatalog() { return TOOL_DEFINITIONS.map(({ name, description, destructive, write }) => ({ name, description, destructive: Boolean(destructive), write: Boolean(write) })); }
export async function dispatchTool(call: ParsedActionCall): Promise<ToolResult> { const def = TOOL_DEFINITIONS.find((t) => t.name === call.name); if (!def) return err(call.id, call.name, "unknown_tool", `Unknown tool: ${call.name}`); if (call.error) return err(call.id, call.name, "invalid_args", call.error); if (!ensureOwner(def.write || def.destructive)) return err(call.id, call.name, "collab_guest_readonly", "Only the collaboration owner can modify this workflow"); const parsed = def.schema.safeParse(call.args); if (!parsed.success) return err(call.id, call.name, "invalid_args", parsed.error.message); try { const result = await (def.handler as (args: unknown) => ToolResult | Promise<ToolResult>)(parsed.data); return { ...result, id: call.id, name: call.name }; } catch (error) { return err(call.id, call.name, "handler_error", error instanceof Error ? error.message : String(error)); } }
export function isDestructiveTool(name: string): boolean { return Boolean(TOOL_DEFINITIONS.find((t) => t.name === name)?.destructive); }
