// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  workflowId: __t.string(),
  workspaceId: __t.string(),
  name: __t.string(),
  nodesJson: __t.string(),
  edgesJson: __t.string(),
  uiStateJson: __t.string(),
  createdAt: __t.string(),
  updatedAt: __t.string(),
  lastModifiedBy: __t.string(),
};
