// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.1.0 (commit 6981f48b4bc1a71c8dd9bdfe5a2c343f6370243d).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddBrainFeedbackReducer from "./add_brain_feedback_reducer";
import ApplyWorkflowOpsReducer from "./apply_workflow_ops_reducer";
import CreateInviteReducer from "./create_invite_reducer";
import CreateWorkflowReducer from "./create_workflow_reducer";
import CreateWorkspaceReducer from "./create_workspace_reducer";
import DeleteBrainDocReducer from "./delete_brain_doc_reducer";
import DeleteWorkflowReducer from "./delete_workflow_reducer";
import DeleteWorkspaceReducer from "./delete_workspace_reducer";
import ImportBrainDocReducer from "./import_brain_doc_reducer";
import ImportWorkflowSnapshotReducer from "./import_workflow_snapshot_reducer";
import ImportWorkspaceReducer from "./import_workspace_reducer";
import JoinWorkspaceReducer from "./join_workspace_reducer";
import RecordBrainViewReducer from "./record_brain_view_reducer";
import RenameWorkflowReducer from "./rename_workflow_reducer";
import RenameWorkspaceReducer from "./rename_workspace_reducer";
import RestoreBrainDocVersionReducer from "./restore_brain_doc_version_reducer";
import SaveBrainDocReducer from "./save_brain_doc_reducer";
import UpdatePresenceReducer from "./update_presence_reducer";
import UpdateWorkflowUiStateReducer from "./update_workflow_ui_state_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import BrainDocRow from "./brain_doc_table";
import BrainDocVersionRow from "./brain_doc_version_table";
import BrainFeedbackRow from "./brain_feedback_table";
import PresenceRow from "./presence_table";
import WorkflowRow from "./workflow_table";
import WorkflowChangeEventRow from "./workflow_change_event_table";
import WorkflowEdgeRow from "./workflow_edge_table";
import WorkflowNodeRow from "./workflow_node_table";
import WorkflowUiStateRow from "./workflow_ui_state_table";
import WorkspaceRow from "./workspace_table";
import WorkspaceInviteRow from "./workspace_invite_table";
import WorkspaceMemberRow from "./workspace_member_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  brainDoc: __table({
    name: 'brain_doc',
    indexes: [
      { accessor: 'id', name: 'brain_doc_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'byWorkspaceId', name: 'brain_doc_workspace_id_idx_btree', algorithm: 'btree', columns: [
        'workspaceId',
      ] },
    ],
    constraints: [
      { name: 'brain_doc_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, BrainDocRow),
  brainDocVersion: __table({
    name: 'brain_doc_version',
    indexes: [
      { accessor: 'byDocId', name: 'brain_doc_version_doc_id_idx_btree', algorithm: 'btree', columns: [
        'docId',
      ] },
    ],
    constraints: [
    ],
  }, BrainDocVersionRow),
  brainFeedback: __table({
    name: 'brain_feedback',
    indexes: [
      { accessor: 'byDocId', name: 'brain_feedback_doc_id_idx_btree', algorithm: 'btree', columns: [
        'docId',
      ] },
    ],
    constraints: [
    ],
  }, BrainFeedbackRow),
  presence: __table({
    name: 'presence',
    indexes: [
      { accessor: 'byIdentity', name: 'presence_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'byWorkspaceId', name: 'presence_workspace_id_idx_btree', algorithm: 'btree', columns: [
        'workspaceId',
      ] },
    ],
    constraints: [
    ],
  }, PresenceRow),
  workflow: __table({
    name: 'workflow',
    indexes: [
      { accessor: 'id', name: 'workflow_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
      { accessor: 'byWorkspaceId', name: 'workflow_workspace_id_idx_btree', algorithm: 'btree', columns: [
        'workspaceId',
      ] },
    ],
    constraints: [
      { name: 'workflow_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorkflowRow),
  workflowChangeEvent: __table({
    name: 'workflow_change_event',
    indexes: [
      { accessor: 'byWorkflowId', name: 'workflow_change_event_workflow_id_idx_btree', algorithm: 'btree', columns: [
        'workflowId',
      ] },
    ],
    constraints: [
    ],
  }, WorkflowChangeEventRow),
  workflowEdge: __table({
    name: 'workflow_edge',
    indexes: [
      { accessor: 'byWorkflowId', name: 'workflow_edge_workflow_id_idx_btree', algorithm: 'btree', columns: [
        'workflowId',
      ] },
    ],
    constraints: [
    ],
  }, WorkflowEdgeRow),
  workflowNode: __table({
    name: 'workflow_node',
    indexes: [
      { accessor: 'byWorkflowId', name: 'workflow_node_workflow_id_idx_btree', algorithm: 'btree', columns: [
        'workflowId',
      ] },
    ],
    constraints: [
    ],
  }, WorkflowNodeRow),
  workflowUiState: __table({
    name: 'workflow_ui_state',
    indexes: [
      { accessor: 'workflowId', name: 'workflow_ui_state_workflow_id_idx_btree', algorithm: 'btree', columns: [
        'workflowId',
      ] },
    ],
    constraints: [
      { name: 'workflow_ui_state_workflow_id_key', constraint: 'unique', columns: ['workflowId'] },
    ],
  }, WorkflowUiStateRow),
  workspace: __table({
    name: 'workspace',
    indexes: [
      { accessor: 'id', name: 'workspace_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'workspace_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorkspaceRow),
  workspaceInvite: __table({
    name: 'workspace_invite',
    indexes: [
      { accessor: 'byTokenHash', name: 'workspace_invite_token_hash_idx_btree', algorithm: 'btree', columns: [
        'tokenHash',
      ] },
      { accessor: 'byWorkspaceId', name: 'workspace_invite_workspace_id_idx_btree', algorithm: 'btree', columns: [
        'workspaceId',
      ] },
    ],
    constraints: [
    ],
  }, WorkspaceInviteRow),
  workspaceMember: __table({
    name: 'workspace_member',
    indexes: [
      { accessor: 'byIdentity', name: 'workspace_member_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
      { accessor: 'byWorkspaceId', name: 'workspace_member_workspace_id_idx_btree', algorithm: 'btree', columns: [
        'workspaceId',
      ] },
    ],
    constraints: [
    ],
  }, WorkspaceMemberRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_brain_feedback", AddBrainFeedbackReducer),
  __reducerSchema("apply_workflow_ops", ApplyWorkflowOpsReducer),
  __reducerSchema("create_invite", CreateInviteReducer),
  __reducerSchema("create_workflow", CreateWorkflowReducer),
  __reducerSchema("create_workspace", CreateWorkspaceReducer),
  __reducerSchema("delete_brain_doc", DeleteBrainDocReducer),
  __reducerSchema("delete_workflow", DeleteWorkflowReducer),
  __reducerSchema("delete_workspace", DeleteWorkspaceReducer),
  __reducerSchema("import_brain_doc", ImportBrainDocReducer),
  __reducerSchema("import_workflow_snapshot", ImportWorkflowSnapshotReducer),
  __reducerSchema("import_workspace", ImportWorkspaceReducer),
  __reducerSchema("join_workspace", JoinWorkspaceReducer),
  __reducerSchema("record_brain_view", RecordBrainViewReducer),
  __reducerSchema("rename_workflow", RenameWorkflowReducer),
  __reducerSchema("rename_workspace", RenameWorkspaceReducer),
  __reducerSchema("restore_brain_doc_version", RestoreBrainDocVersionReducer),
  __reducerSchema("save_brain_doc", SaveBrainDocReducer),
  __reducerSchema("update_presence", UpdatePresenceReducer),
  __reducerSchema("update_workflow_ui_state", UpdateWorkflowUiStateReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.1.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}
