// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  workspaceId: __t.string().name("workspace_id"),
  workflowId: __t.string().name("workflow_id"),
  identity: __t.identity(),
  displayName: __t.string().name("display_name"),
  selectedNodeId: __t.option(__t.string()).name("selected_node_id"),
  lastSeenAt: __t.string().name("last_seen_at"),
});
