// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const BrainDoc = __t.object("BrainDoc", {
  id: __t.string(),
  workspaceId: __t.string(),
  title: __t.string(),
  contentJson: __t.string(),
  createdAt: __t.string(),
  updatedAt: __t.string(),
  deletedAt: __t.option(__t.string()),
});
export type BrainDoc = __Infer<typeof BrainDoc>;

export const BrainDocVersion = __t.object("BrainDocVersion", {
  docId: __t.string(),
  versionId: __t.string(),
  contentJson: __t.string(),
  createdAt: __t.string(),
});
export type BrainDocVersion = __Infer<typeof BrainDocVersion>;

export const BrainFeedback = __t.object("BrainFeedback", {
  docId: __t.string(),
  identity: __t.identity(),
  type: __t.string(),
  comment: __t.string(),
  createdAt: __t.string(),
});
export type BrainFeedback = __Infer<typeof BrainFeedback>;

export const Presence = __t.object("Presence", {
  workspaceId: __t.string(),
  workflowId: __t.string(),
  identity: __t.identity(),
  displayName: __t.string(),
  selectedNodeId: __t.option(__t.string()),
  lastSeenAt: __t.string(),
});
export type Presence = __Infer<typeof Presence>;

export const Workflow = __t.object("Workflow", {
  id: __t.string(),
  workspaceId: __t.string(),
  name: __t.string(),
  createdAt: __t.string(),
  updatedAt: __t.string(),
  lastModifiedBy: __t.string(),
});
export type Workflow = __Infer<typeof Workflow>;

export const WorkflowChangeEvent = __t.object("WorkflowChangeEvent", {
  workflowId: __t.string(),
  eventType: __t.string(),
  nodeId: __t.option(__t.string()),
  details: __t.string(),
  timestamp: __t.string(),
});
export type WorkflowChangeEvent = __Infer<typeof WorkflowChangeEvent>;

export const WorkflowEdge = __t.object("WorkflowEdge", {
  workflowId: __t.string(),
  edgeId: __t.string(),
  source: __t.string(),
  target: __t.string(),
  handlesJson: __t.string(),
  dataJson: __t.string(),
  updatedAt: __t.string(),
  updatedBy: __t.string(),
});
export type WorkflowEdge = __Infer<typeof WorkflowEdge>;

export const WorkflowNode = __t.object("WorkflowNode", {
  workflowId: __t.string(),
  nodeId: __t.string(),
  type: __t.string(),
  positionJson: __t.string(),
  dataJson: __t.string(),
  updatedAt: __t.string(),
  updatedBy: __t.string(),
});
export type WorkflowNode = __Infer<typeof WorkflowNode>;

export const WorkflowUiState = __t.object("WorkflowUiState", {
  workflowId: __t.string(),
  uiStateJson: __t.string(),
});
export type WorkflowUiState = __Infer<typeof WorkflowUiState>;

export const Workspace = __t.object("Workspace", {
  id: __t.string(),
  name: __t.string(),
  createdAt: __t.string(),
  updatedAt: __t.string(),
});
export type Workspace = __Infer<typeof Workspace>;

export const WorkspaceInvite = __t.object("WorkspaceInvite", {
  workspaceId: __t.string(),
  tokenHash: __t.string(),
  createdAt: __t.string(),
  revokedAt: __t.option(__t.string()),
});
export type WorkspaceInvite = __Infer<typeof WorkspaceInvite>;

export const WorkspaceMember = __t.object("WorkspaceMember", {
  workspaceId: __t.string(),
  identity: __t.identity(),
  displayName: __t.string(),
  role: __t.string(),
  joinedAt: __t.string(),
});
export type WorkspaceMember = __Infer<typeof WorkspaceMember>;
