// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  workflowId: __t.string().name("workflow_id"),
  edgeId: __t.string().name("edge_id"),
  source: __t.string(),
  target: __t.string(),
  handlesJson: __t.string().name("handles_json"),
  dataJson: __t.string().name("data_json"),
  updatedAt: __t.string().name("updated_at"),
  updatedBy: __t.string().name("updated_by"),
});
