// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  workflowId: __t.string().name("workflow_id"),
  nodeId: __t.string().name("node_id"),
  type: __t.string(),
  positionJson: __t.string().name("position_json"),
  dataJson: __t.string().name("data_json"),
  updatedAt: __t.string().name("updated_at"),
  updatedBy: __t.string().name("updated_by"),
});
